// This header file was auto-generated by ClassMate++
// Created: 1 Aug 2019 10:48:43 am
// Copyright (c) 2019, HurleyWorks

#pragma once

#include "OpenglUtil.h"

using Eigen::Vector2i;
using Eigen::Vector4f;

using OpenglWindowHandle = std::unique_ptr<class OpenglWindow>;
class InputHandler;

class OpenglWindow
{

 public:
	OpenglWindow (InputHandler & input);
	~OpenglWindow ();

	void renderBegin(const Vector4f & clearColor);
	void renderEnd(bool wait);

	void renderImage(ImagePixels && pixels, ImageInfo & spec);
	void renderImage(ImageFloatPixels && pixels, ImageInfo& spec);

	void create(const Vector2i & size, const std::string & caption,
				bool resizable = true, bool fullscreen = false, int colorBits = 8,
				int alphaBits = 8, int depthBits = 24, int stencilBits = 8,
				int nSamples = 0, unsigned int glMajor = 4, unsigned int glMinor = 3);

	InputHandler& getInput() { return input; }

 private:
	 InputHandler & input;
	 GLFWwindow * window = nullptr;
	 NVGcontext * nanovgContext = nullptr;
	 bool gladInitialized = false;

	 bool running = true;
	 bool isFloatImage = false;

	 // full screen textured quad from 2 triangles
	 OpenglUtil::FullScreenQuad quad;
	 ImagePixels imagePixels;
	 ImageFloatPixels floatPixels;
	 GLuint textureID = 0;
	 GLuint floatTextureID = 0;

	 // handle window events here
	 void onWindowFocus(int focused);
	 void onWindowResize(int width, int height);
	 void onWindowClose();
	
}; // end class OpenglWindow
