// This header file was auto-generated by ClassMate++
// Created: 18 Aug 2019 4:00:14 pm
// Copyright (c) 2019, HurleyWorks

#pragma once

class GeometryHandler
{

 public:
	GeometryHandler ();
	~GeometryHandler ();


}; // end class GeometryHandler
