// This source file was auto-generated by ClassMate++
// Created: 18 Aug 2019 4:00:14 pm
// Copyright (c) 2019, HurleyWorks
#include "berserkpch.h"
#include "MaterialHandler.h"

// ctor
MaterialHandler::MaterialHandler ()
{	
}

// dtor
MaterialHandler::~MaterialHandler ()
{	
}

