// This header file was auto-generated by ClassMate++
// Created: 17 Aug 2019 3:42:21 pm
// Copyright (c) 2019, HurleyWorks

#pragma once
#include "../../RenderLayer.h"
#include "OptixData.h"

class OptixLayer : public RenderLayer
{

 public:
	OptixLayer (const PropertyService& properties);
	~OptixLayer ();

	void onAttach() override;
	void onDetach() override;

	void onUpdate() override;
	void onInput(const InputEvent& input) override;

private:
	ContextHandle context = nullptr;
	Modules modules;

}; // end class OptixLayer
