// This header file was auto-generated by ClassMate++
// Created: 22 Feb 2019 8:55:26 pm
// Copyright (c) 2019, HurleyWorks

#pragma once
#include "RenderLayer.h"

// https://www.youtube.com/user/TheChernoProject

class RenderStack
{
 
  public:
	 RenderStack() = default;
	 ~RenderStack() = default;

	 void pushLayer(RenderLayerRef & layer);
	 void pushOverlay(RenderLayerRef & overlay);
	 void popLayer(RenderLayerRef & layer);
	 void popOverlay(RenderLayerRef & overlay);

	 std::vector<RenderLayerRef>::iterator begin() { return layers.begin(); }
	 std::vector<RenderLayerRef>::iterator end() { return layers.end(); }

  private:
	std::vector<RenderLayerRef> layers;
	unsigned int layerInsertIndex = 0;

}; // end class RenderStack
