// This source file was auto-generated by ClassMate++
// Created: 17 Aug 2019 3:42:21 pm
// Copyright (c) 2019, HurleyWorks
#include "berserkpch.h"
#include "RenderLayer.h"

// ctor
RenderLayer::RenderLayer ()
{	
}

// dtor
RenderLayer::~RenderLayer ()
{	
}

