// This header file was auto-generated by ClassMate++
// Created: 18 Aug 2019 4:00:14 pm
// Copyright (c) 2019, HurleyWorks

#pragma once

#include "LaunchParams.h"

class OptixScene : public OptixEngine
{
	using RayGenSbtRecord = SbtRecord<RayGenData>;
	using MissSbtRecord = SbtRecord<MissData>;
	using HitGroupSbtRecord = SbtRecord<HitData>;

 public:
	OptixScene (const PropertyService& properties, const OptixConfig& config);
	~OptixScene ();

	void init(CameraHandle& camera, const json& groups) override;
	void addRenderable(RenderableNode& node) override;

	void render(CameraHandle& camera) override
	{
		if (gAccel == 0) return;
		
		// update our settings on gpu
		syncCamera(camera);
		syncBackgoundColor();
		syncMeshColor();

		renderer->render(camera, OptixEngine::getPtr());
	}
	
 private:
	RendererHandle renderer = nullptr;
	
	CUDABuffer vertexBuffer;
	CUDABuffer indexBuffer;
	CUDABuffer asBuffer;

	RayGenSbtRecord rg_sbt;
	MissSbtRecord ms_sbt;
	HitGroupSbtRecord hg_sbt;

	void buildSBT(CameraHandle& camera) override;

	void syncCamera(CameraHandle& camera);
	void updateCamera(CameraHandle& camera);
	void syncBackgoundColor();
	void syncMeshColor();

}; // end class OptixScene
