// This header file was auto-generated by ClassMate++
// Created: 18 Aug 2019 4:00:14 pm
// Copyright (c) 2019, HurleyWorks

#pragma once

#include <optix7_core/optix7_core.h>

class OptixScene : public OptixEngine
{

 public:
	OptixScene (const PropertyService& properties);
	~OptixScene ();

	void init(CameraHandle& camera) override;
	void addPipeline(PipelineType type, const json& groups, OptixConfig& config ) override;
	void addRenderable(RenderableNode& node) override;
	void clearScene() override;
	void onInput(const InputEvent& input) override;

	void render(CameraHandle& camera) override
	{		
		if (!ok) return;

		renderer->render(camera, OptixEngine::getPtr(), input);
	}
	
 private:
	RendererHandle renderer = nullptr;
	bool ok = true;
	InputEvent input;
	
}; // end class OptixScene
