
// This source file was auto-generated by ClassMate++
// Created: 18 Aug 2019 4:00:14 pm
// Copyright (c) 2019, HurleyWorks

using juce::String;
using juce::File;
using juce::StringArray;
using mace::FileServices;

// ctor
OptixEngine::OptixEngine (const PropertyService& properties)
	: properties(properties),
	  renderer(properties)
{	
	
}

// dtor
OptixEngine::~OptixEngine ()
{	
}

void OptixEngine::init()
{
	context = OptixContext::create();

	std::string resourceFolder = properties.renderProps->getVal<std::string>(RenderKey::ResourceFolder);
	File f(resourceFolder);
	if (!f.exists())
		throw std::runtime_error("No resource folder found at " + resourceFolder);

	String ptxFolder = resourceFolder + "/ptx";
	StringArray ptxFiles;
	String wildCard("*.ptx");
	FileServices::getFiles(ptxFolder, ptxFiles, wildCard);

	for (auto ptx : ptxFiles)
	{
		File f(ptx);
		if (!f.existsAsFile()) continue;

		ModuleHandle mod = OptixMod::create();
		String ptxStr = f.loadFileAsString();
		mod->createFromPtx(context, ptxStr.toStdString());

		modules.push_back(mod);
	}
}

