// This header file was auto-generated by ClassMate++
// Created: 26 Sep 2019 2:36:23 pm
// Copyright (c) 2019, HurleyWorks

#pragma  once

using sabi::PixelBufferHandle;

class OptixImageHandler
{
public:
	OptixImageHandler();
	~OptixImageHandler();

	void addImage(PixelBufferHandle& image);

private:

	std::vector<cudaArray_t> images;
};

