
// This source file was auto-generated by ClassMate++
// Created: 18 Aug 2019 4:00:14 pm
// Copyright (c) 2019, HurleyWorks


// ctor
OptixEngine::OptixEngine (const PropertyService& properties,const OptixConfig& config)
	: properties(properties),
	  config(config)
{	
	ctx = OptixContext::create(config.options.context_options);
}

// dtor
OptixEngine::~OptixEngine ()
{	
}

