// This header file was auto-generated by ClassMate++
// Created: 18 Aug 2019 4:00:14 pm
// Copyright (c) 2019, HurleyWorks

#pragma once

using sabi::CameraHandle;

class OptixRenderer
{

 public:
	OptixRenderer (const PropertyService& properties);
	~OptixRenderer ();

	void init(int screenWidth, int screenHeight);
	void render(CameraHandle& camera, OptixTraversableHandle & gas_handle, OptixPipeline pipeline, const OptixShaderBindingTable& sbt);

 private:
	 PropertyService properties;
	 CUDAOutputBuffer<uchar4> output_buffer;

}; // end class OptixRenderer
