// This header file was auto-generated by ClassMate++
// Created: 18 Aug 2019 4:00:14 pm
// Copyright (c) 2019, HurleyWorks

#pragma once

class OptixEngine
{
 public:
	OptixEngine (const PropertyService& properties);
	~OptixEngine ();

	void init(const OptixConfig& config, CameraHandle& camera);
	void render(CameraHandle& camera); //  { renderer.render(camera); }

 private:
	PropertyService properties;
	OptixRenderer renderer;
	ContextHandle context = nullptr;
	OptixModule module = nullptr;
	OptixPipeline pipeline = nullptr;
	OptixShaderBindingTable sbt = {};
	OptixTraversableHandle gas_handle;
	CUDAOutputBuffer<uchar4> output_buffer;

	
}; // end class OptixEngine
