// This source file was auto-generated by ClassMate++
// Created: 18 Aug 2019 4:00:14 pm
// Copyright (c) 2019, HurleyWorks


// ctor
OptixRenderer::OptixRenderer(unsigned int screenWidth, unsigned int screenHeight)
	: width(screenWidth),
	  height(screenHeight)
{	
}

// dtor
OptixRenderer::~OptixRenderer ()
{	
}
