// This source file was auto-generated by ClassMate++
// Created: 12 Sep 2019 6:29:23 am
// Copyright (c) 2019, HurleyWorks


// ctor
OptixAccel::OptixAccel ()
{	
	accel_options.buildFlags = OPTIX_BUILD_FLAG_ALLOW_COMPACTION;
	accel_options.operation = OPTIX_BUILD_OPERATION_BUILD;
}

// dtor
OptixAccel::~OptixAccel ()
{	
}

