// This header file was auto-generated by ClassMate++
// Created: 18 Aug 2019 4:00:14 pm
// Copyright (c) 2019, HurleyWorks

#pragma once

#include "EngineData.h"

using Eigen::Vector4f;

// the bulk of this code is from the Optix7 Whitted sample
class PrimitiveEngine : public OptixEngine
{

 public:
	PrimitiveEngine (const PropertyService& properties, const OptixConfig& config);
	~PrimitiveEngine ();

	void init(CameraHandle& camera) override;
	void render(CameraHandle& camera) override
	{
	
	}

 private:
	WhittedState state;
    unsigned int max_trace = 10;

	bool resize_dirty = false;
	bool restartAccum = true;
	Vector4f lastBackGround = Vector4f::Constant(0.0);

	
}; // end class PrimitiveEngine
