
// This source file was auto-generated by ClassMate++
// Created: 18 Aug 2019 4:00:14 pm
// Copyright (c) 2019, HurleyWorks

#include "PrimitiveEngine.h"

using juce::String;
using juce::File;
using juce::StringArray;
using mace::FileServices;
using Eigen::Vector4f;
using Eigen::Vector3f;

// the bulk of this code is from the Optix7 optixWhitted sample

// ctor
PrimitiveEngine::PrimitiveEngine (const PropertyService& properties, const OptixConfig& config)
	: OptixEngine(properties, config)
{	
	
}

// dtor
PrimitiveEngine::~PrimitiveEngine ()
{	
	try
	{
		



		
	}
	catch (std::exception& e)
	{
		LOG(CRITICAL) << e.what();
	}
	catch (...)
	{
		LOG(CRITICAL) << "Caught unknown exception";
	}
}

void PrimitiveEngine::init(CameraHandle& camera)
{
	
}

