// This header file was auto-generated by ClassMate++
// Created: 18 Aug 2019 6:10:35 am
// Copyright (c) 2019, HurleyWorks

#pragma once
#include <sabi_core/sabi_core.h>

using sabi::InputEvent;
using sabi::CameraHandle;
using Eigen::Vector2f;

class Controller
{
	// https://www.bogotobogo.com/DesignPatterns/mvc_model_view_controller_pattern.php
	// Intermediary between Model & View
	// Updates the view when the model changes
	// Updates the model when the user manipulates the view
	// Typically where the app logic lives

 public:
	Controller (const PropertyService& properties);
	~Controller() = default;
		
	void onInput(const InputEvent& e, CameraHandle& camera);

 private:
	PropertyService properties;
	Vector2f mouseCoords;

}; // end class Controller
