// This source file was auto-generated by ClassMate++
// Created: 18 Aug 2019 6:10:35 am
// Copyright (c) 2019, HurleyWorks

#include "Controller.h"

// ctor
Controller::Controller ()
{	
}

// dtor
Controller::~Controller ()
{	
}

void Controller::onInput(const InputEvent& e)
{
	switch (e.getType())
	{
		case InputEvent::Press:
			//LOG(DBUG) << "PRESS";
			break;

		case InputEvent::Release:
			//LOG(DBUG) << "RELEASE";
			break;

		case InputEvent::Move:
			//LOG(DBUG) << "MOVE";
			break;

		case InputEvent::Drag:
			LOG(DBUG) << "Dragging: " << e.getX() << ", " << e.getY();
			break;
	}
}

