// This header file was auto-generated by ClassMate++
// Created: 18 Aug 2019 6:10:35 am
// Copyright (c) 2019, HurleyWorks

#pragma once

#include <sabi_core/sabi_core.h>

using handleType = std::unique_ptr<uint8_t[], void(*)(void*)>;

class Model
{
	//https://www.bogotobogo.com/DesignPatterns/mvc_model_view_controller_pattern.php
	// Manages the app data and state
	// Not concerned with UI or presentation
	// Often persists somewhere
	// Same model should be reusable, unchanged in different interfaces

 public:
	Model ();
	~Model ();

	void loadImage(const std::string& path, ImagePixels & image, ImageInfo & spec);
	void onDrop(const std::vector<std::string>& fileList);
	
}; // end class Model
