// This header file was auto-generated by ClassMate++
// Created: 18 Aug 2019 4:00:14 pm
// Copyright (c) 2019, HurleyWorks

#pragma once
#include <sabi_core/sabi_core.h>

using sabi::CameraHandle;

class OptixRenderer
{

 public:
	OptixRenderer ();
	~OptixRenderer ();

	void render(CameraHandle& camera);

}; // end class OptixRenderer
