// This header file was auto-generated by ClassMate++
// Created: 18 Aug 2019 6:10:35 am
// Copyright (c) 2019, HurleyWorks

#pragma once

class NanoguiLayer;
struct PropertyService;
using juce::StringArray;

class View
{
	// https://www.bogotobogo.com/DesignPatterns/mvc_model_view_controller_pattern.php
	// Present the Model to the user in an appropriate interface
	// Allows user to manipulate data through the Controller
	// Does not store any data except to cache state
	// Easily reusable & configurable to display different data

 public:
	View (const PropertyService & properties);
	~View ();
	
	void create(NanoguiLayer* const gui);

	// this fixed crashing in MessageDialog!
	EIGEN_MAKE_ALIGNED_OPERATOR_NEW

 private:
	 PropertyService properties;
	 NanoguiLayer* gui = nullptr; // owned by App, don't delete
	 NVGcontext* nvgCtx = nullptr;  // owned by App, don't delete
	
	 // button colors
	 int r = 25;
	 int g = 50;
	 int b = 75;
	 int a = 30;

	 // label colors
	 int r1 = 255;
	 int g1 = 100;
	 int b1 = 0;
	 int a1 = 255;

	 const StringArray getSceneInfo();

}; // end class View
