// This source file was auto-generated by ClassMate++
// Created: 26 Jan 2019 8:47:47 pm
// Copyright (c) 2019, HurleyWorks

#include "berserkpch.h"
#include "App.h"

namespace Jahley
{

	// ctor
	App::App (bool windowApp)
		: windowApp(windowApp),
		  errorCallback(std::bind(&App::onFatalError, this, std::placeholders::_1)),
		  preCrashCallback(std::bind(&App::preCrash, this)),
		  log(errorCallback, preCrashCallback)
	{	
		
	}

	// dtor
	App::~App ()
	{	
	
	}

	void App::run()
	{
		while (isRunning)
		{
			// let the client update
			update();
		}
	}

	// preCrash
	void App::preCrash()
	{
		
#if (defined(WIN32) || defined(_WIN32) || defined(__WIN32__))
		__debugbreak();
#endif
	}

	// onFatalError
	void App::onFatalError(g3::FatalMessagePtr fatal_message)
	{
		LOG(WARNING) << fatal_message.get()->toString();

		// now ready to exit, instead of reinventing the wheel we do it the g3log way
		g3::internal::pushFatalMessageToLogger(fatal_message);
	}

}