// This header file was auto-generated by ClassMate++
// Created: 18 Jul 2016 7:57:36 pm
// Copyright (c) 2016, HurleyWorks

#pragma once

#include "../AppConfig.h"

using FatalErrorCallback = std::function<void(g3::FatalMessagePtr)>;
using PreCrashCallback = std::function<void()>;

class LogHandler
{

 public:
	LogHandler(FatalErrorCallback crashCallback, PreCrashCallback precrashCallback);
	~LogHandler() = default;

 private:
	std::unique_ptr<g3::LogWorker> worker;

}; // end class LogHandler