// This source file was auto-generated by ClassMate++
// Created: 18 Aug 2019 6:10:35 am
// Copyright (c) 2019, HurleyWorks

#include "Controller.h"
using Eigen::Vector2f;

// ctor
Controller::Controller ()
{	
}

// dtor
Controller::~Controller ()
{	
}

void Controller::onInput(const InputEvent& e, CameraHandle& camera)
{
	switch (e.getType())
	{
		case InputEvent::Press:
			camera->startTracking();
			camera->track(Vector2f(e.getX(), e.getY()));
			break;

		case InputEvent::Release:
			camera->setDirty(false);
			break;

		case InputEvent::Move:
			break;

		case InputEvent::ScrollUp:
			

			break;

		case InputEvent::Drag:
			camera->track(Vector2f(e.getX(), e.getY()));
			camera->setDirty(true);
			break;
	}
}

