// This header file was auto-generated by ClassMate++
// Created: 14 Jul 2016 3:06:26 pm
// Copyright (c) 2016, HurleyWorks

#pragma once

class LWSN
{

 public:
	LWSN ();
	~LWSN ();
	
}; // end class LWSN
