// This header file was auto-generated by ClassMate++
// Created: 22 Feb 2019 8:55:26 pm
// Copyright (c) 2019, HurleyWorks

#pragma  once

// Memory Allocation Functions
#if defined(JUCE_WINDOWS)
#define memalign(a,b) _aligned_malloc(b, a)
//#define thread_local  __declspec( thread )
#elif defined(JUCE_MAC)
#endif

inline void* AllocAligned(size_t size)
{
#ifndef L1_CACHE_LINE_SIZE
#define L1_CACHE_LINE_SIZE 64
#endif
	return memalign(L1_CACHE_LINE_SIZE, size);
}

inline void FreeAligned(void *ptr)
{
#ifdef JUCE_WINDOWS 
	_aligned_free(ptr);
#else
	free(ptr);
#endif 
}