// This header file was auto-generated by ClassMate++
// Created: 18 Aug 2019 6:10:35 am
// Copyright (c) 2019, HurleyWorks

#pragma once

#include "Compiler.h"

class Model : public CsSignal::SlotBase
{
	//https://www.bogotobogo.com/DesignPatterns/mvc_model_view_controller_pattern.php
	// Manages the app data and state
	// Not concerned with UI or presentation
	// Often persists somewhere
	// Same model should be reusable, unchanged in different interfaces

 public:
	Model() = default;
	~Model() = default;

	void findCudaFiles(const std::string& path) { activeObject.call(&Compiler::findCudaFiles, path); }
	void setPtxOutputFolder(const std::string& path) { activeObject.call(&Compiler::setPtxOutputFolder, path); }
	void addIncludePath(const std::string include) { activeObject.call(&Compiler::addIncludePath, include); }

	void runNVCC(bool createPtxHeaders) { activeObject.call(&Compiler::runNVCC, createPtxHeaders); }

	void onDrop(const std::vector<std::string>& fileList);
	
 private:
	// run on an ActiveObject so the app remains responsive while compiling
	concurrent<Compiler> activeObject;

}; // end class Model
