// This header file was auto-generated by ClassMate++
// Created: 2 Sep 2019 5:16:51 am
// Copyright (c) 2019, HurleyWorks

#pragma  once

using sabi::Surface;
using sabi::MeshBuffers;
using sabi::MeshBuffersHandle;

using igl::read_triangle_mesh;
using igl::per_vertex_normals;

using LoadMeshCallback = std::function<void(MeshBuffersHandle)>;

class ActiveLoader 
{

 public:
	ActiveLoader() = default;
	~ActiveLoader() = default;
	
	void loadMesh(const std::string& path, LoadMeshCallback& callback)
	{
		Eigen::MatrixXd V;
		Eigen::MatrixXi F;
		if (!read_triangle_mesh(path, V, F))
		{
			LOG(CRITICAL) << "load mesh failed for: " << path;
			return;
		}

		MeshBuffersHandle m = std::make_shared<MeshBuffers>();
		m->V = V.transpose().cast<float>(); // Libigl needs to be transposed

		// Compute per-vertex normals
		Eigen::MatrixXd N;
		per_vertex_normals(V, F, N);
		m->N = N.transpose().cast<float>(); // Libigl needs to be transposed

		MatrixXu indices = F.cast<unsigned>();
		Surface s;
		s.indices() = indices.transpose(); // Libigl needs to be transposed
		m->S.push_back(s);

		callback(m);
	}

}; // end class ActiveLoader
