// This header file was auto-generated by ClassMate++
// Created: 18 Mar 2019 8:01:18 pm
// Copyright (c) 2019, HurleyWorks

#pragma  once

using Eigen::Vector4f;

struct Material
{
	Vector4f base_color = { 1.0f,1.0f, 1.0f, 1.0f };
	float metallic = 1.0f;
	float roughness = 1.0f;

	TextureHandlerRef base_color_tex = nullptr;
	TextureHandlerRef metallic_roughness_tex = nullptr;
	TextureHandlerRef normal_tex = nullptr;
};

using Materials = std::vector<Material>;