// This header file was auto-generated by ClassMate++
// Created: 18 Mar 2019 8:01:18 pm
// Copyright (c) 2019, HurleyWorks

#pragma  once

enum BrdfType
{
	DISNEY, GLASS
};


struct Material
{
	Material()
	{
		color = Eigen::Vector3f(1.0f, 1.0f, 1.0f);
		emission = Eigen::Vector3f(0.0f, 0.0f, 0.0f);
		metallic = 0.0;
		subsurface = 0.0f;
		specular = 0.5f;
		roughness = 0.5f;
		specularTint = 0.0f;
		anisotropic = 0.0f;
		sheen = 0.0f;
		sheenTint = 0.5f;
		clearcoat = 0.0f;
		clearcoatGloss = 1.0f;
		brdf = DISNEY;
		albedoID = 0;
	}

	int albedoID;
	Eigen::Vector3f color;
	Eigen::Vector3f emission;
	float metallic;
	float subsurface;
	float specular;
	float roughness;
	float specularTint;
	float anisotropic;
	float sheen;
	float sheenTint;
	float clearcoat;
	float clearcoatGloss;
	BrdfType brdf;
};