// This header file was auto-generated by ClassMate++
// Created: 10 Feb 2018 9:21:04 am
// Copyright (c) 2018, HurleyWorks

#pragma  once

struct MeshBuffers
{
	Surfaces S;   // collection of triangles with different materials
	MatrixXf V;   // vertices
	MatrixXf D;   // displaced vertices
	MatrixXf N;   // vertex normals
	MatrixXf RV;  // reduced by InstantMeshes vertices
	MatrixXu RF;  // reduced by InstantMesh faces;

	// for some reason I can't use the variable name RN here
	// because it fails to compile in Retopology.cpp for no good 
	// reason that I can see so NR is fine but RN doesn't work
	MatrixXf NR;  // reduced by InstantMesh normals 

	size_t faceCount = 0;
	
	size_t pointCount() { return V.cols(); }
	size_t triangleCount() { return faceCount; }
	
	void reset()
	{
		V.resize(3, 0);
		N.resize(3, 0);
		D.resize(3, 0);
		RV.resize(3, 0);
		RF.resize(3, 0);
		NR.resize(3, 0);
		S.clear();
	}

	void getAllSurfaceIndices(MatrixXu & allIndices)
	{
		faceCount = 0;
		for (auto s : S)
		{
			faceCount += s.triangleCount();
		}

		allIndices.resize(3, faceCount);

		int index = 0;
		for (auto s : S)
		{
			size_t triCount = s.triangleCount();

			for (int i = 0; i < triCount; i++)
				allIndices.col(index++) = s.indices().col(i);
		}
	}
};

using MeshBuffersHandle = std::shared_ptr<MeshBuffers>;