
// This source file was auto-generated by ClassMate++
// Created: 23 Jan 2018 7:09:22 pm
// Copyright (c) 2018, HurleyWorks

// ctor
NormalizedClump::NormalizedClump ()
	: LoadStrategy()
{	
}

// dtor
NormalizedClump::~NormalizedClump ()
{	
}

// addNextItem
void NormalizedClump::addNextItem(SpaceTime & spacetime)
{
	// place the next obj without intersecting any others
	// as long as their size has been normalized
	Eigen::Vector3f v;
	float d = 1.6f;
	computeNextSpot(objIndex++, d, v);

	spacetime.worldTransform.translation() = v;
	spacetime.previousWorldTransform = spacetime.worldTransform;
}

// computeNextSpot
void NormalizedClump::computeNextSpot(int index, float density, Eigen::Vector3f & spot)
{
	// from the Worley man
	double r = std::sqrt(index) / density;

	// The magic phi angle of about 137.5 degrees, in radians
	// http://cosmometry.net/phi-rotation-angles
	double theta = index * 3.8832220774509331547;
	double x = r * std::sin(theta);
	double z = r * std::cos(theta);

	spot[0] = (float)x;
	spot[1] = 0.0f;
	spot[2] = (float)z;
}