// This source file was auto-generated by ClassMate++
// Created: 29 Dec 2018 3:47:40 pm
// Copyright (c) 2018, HurleyWorks


// ctor
WorldItem::WorldItem()
{
	
}

// dtor
WorldItem::~WorldItem()
{
	
}

RenderableNode WorldItem::createInstance()
{
	RenderableNode instance = WorldItem::create();

	instance->setDescription(Renderable::description());
	instance->setSpacetime(Renderable::getSpaceTime());
	instance->setState(Renderable::getState());
	
	// instances have no mesh!
	instance->setMesh(nullptr);
	instance->setInstancedFrom(getPtr());

	++instanceCount;
	instance->setName(getName() + "_instance_" + std::to_string(instanceCount));
	
	return instance;
}

