// This header file was auto-generated by ClassMate++
// Created: 29 Aug 2019 3:54:59 pm
// Copyright (c) 2019, HurleyWorks

#pragma once

#include <optix7_core/optix7_core.h>

using juce::String;

class SceneConfig
{

public:
	SceneConfig(const PropertyService& properties);
	~SceneConfig();

	void init();

	const json& getProgramGroups(PipelineType type);
	const OptixConfig& getOptixConfig(PipelineType type);

 private:
	PropertyService properties;
	String configFolder;
	json emptyGroup;

	json pickingGroups;
	json simplestGroups;
	json whittedGroups;

	OptixConfig pickingConfig;
	OptixConfig whittedConfig;
	OptixConfig defaultConfigs;

	const json& getPickingPrograms();
	const json& getWhittedPrograms();

	const OptixConfig& getPickingConfigs() { return pickingConfig; }
	const OptixConfig& getWhittedConfigs() { return whittedConfig; }

}; // end class SceneConfig
